// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`
	IV            string `json:"iv"`
	EncryptedData string `json:"encryptedData"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type PetInfo struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Breed        string `json:"breed"`
	DateOfBirth  string `json:"date_of_birth"`
	Gender       string `json:"gender"`
	OwnerName    string `json:"owner_name"`
	OwnerContact string `json:"owner_contact"`
	Note         string `json:"note"`
	CreateTime   string `json:"create_string,optional"`
	UpdateTime   string `json:"update_string,optional"`
	DeleteTime   string `json:"delete_string,optional"`
	DelState     string `json:"del_state"`
}

type PetReq struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Breed        string `json:"breed"`
	DateOfBirth  string `json:"date_of_birth"`
	Gender       string `json:"gender"`
	OwnerName    string `json:"owner_name"`
	OwnerContact string `json:"owner_contact"`
	Note         string `json:"note"`
}

type PetResp struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Breed        string `json:"breed"`
	DateOfBirth  string `json:"date_of_birth"`
	Gender       string `json:"gender"`
	OwnerName    string `json:"owner_name"`
	OwnerContact string `json:"owner_contact"`
	Note         string `json:"note"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
	DeleteTime   string `json:"delete_time"`
	DelState     string `json:"del_state"`
	Version      string `json:"version"`
}

type ThirdPaymentWxPayReq struct {
	OrderSn     string `json:"orderSn"`
	ServiceType string `json:"serviceType"`
}

type ThirdPaymentWxPayResp struct {
	Appid     string `json:"appid"`
	NonceStr  string `json:"nonceStr"`
	PaySign   string `json:"paySign"`
	Package   string `json:"package"`
	Timestamp string `json:"timestamp"`
	SignType  string `json:"signType"`
}

type ThirdPaymentWxPayCallbackReq struct {
}

type ThirdPaymentWxPayCallbackResp struct {
	ReturnCode string `json:"return_code"`
}

type CreateCatOrderReq struct {
	CatId         int64  `json:"homestayId"`
	IsFood        bool   `json:"isFood"`
	LiveStartTime int64  `json:"liveStartTime"`
	LiveEndTime   int64  `json:"liveEndTime"`
	LivePeopleNum int64  `json:"livePeopleNum"`
	Remark        string `json:"remark"`
}

type CreateCatOrderResp struct {
	OrderSn string `json:"orderSn"`
}

type UserCatOrderListView struct {
	Sn              string  `json:"sn"`              //单号
	Title           string  `json:"title"`           //标题
	SubTitle        string  `json:"subTitle"`        //副标题
	CatId           int64   `json:"homestayId"`      //民宿id
	Cover           string  `json:"cover"`           //封面
	OrderTotalPrice float64 `json:"orderTotalPrice"` //订单总价格
	CreateTime      int64   `json:"createTime"`      //下单时间
	TradeState      int64   `json:"tradeState"`      //-1: 已取消 0:待支付 1:未使用 2:已使用  3:已退款 4:已过期
	LiveStartDate   int64   `json:"liveStartDate"`   //入驻开始日期
	LiveEndDate     int64   `json:"liveEndDate"`     //入驻结束日期
	TradeCode       string  `json:"tradeCode"`       //交易码
}

type UserCatOrderListReq struct {
	LastId     int64 `json:"lastId"`
	PageSize   int64 `json:"pageSize"`
	TradeState int64 `json:"tradeState"` //-99:全部 0:代支付订单 1:有效订单
}

type UserCatOrderListResp struct {
	List []UserCatOrderListView `json:"list"`
}

type UserCatOrderDetailReq struct {
	Sn string `json:"sn"`
}

type UserCatOrderDetailResp struct {
	Sn              string  `json:"sn"`                 //单号
	UserId          int64   `json:"userId"`             //用户id
	CatId           int64   `json:"homestayId"`         //民宿id
	Title           string  `json:"title"`              //标题
	SubTitle        string  `json:"subTitle"`           //副标题
	Cover           string  `json:"cover"`              //封面
	Info            string  `json:"info"`               //介绍
	FoodInfo        string  `json:"foodInfo"`           //餐食标准
	FoodPrice       float64 `json:"foodPrice"`          //餐食价格(分)
	CatPrice        float64 `json:"homestayPrice"`      //民宿价格(分)
	MarketCatPrice  float64 `json:"marketCatPrice"`     //民宿市场价格(分)
	CatBusinessId   float64 `json:"homestayBusinessId"` //店铺id
	CatUserId       float64 `json:"homestayUserId"`     //店铺房东id
	OrderTotalPrice float64 `json:"orderTotalPrice"`    //订单总价格
	CreateTime      int64   `json:"createTime"`         //下单时间
	TradeState      int64   `json:"tradeState"`         //-1: 已取消 0:待支付 1:未使用 2:已使用  3:已退款 4:已过期
	LiveStartDate   int64   `json:"liveStartDate"`      //入驻开始日期
	LiveEndDate     int64   `json:"liveEndDate"`        //入驻结束日期
	TradeCode       string  `json:"tradeCode"`          //交易码
	FoodTotalPrice  float64 `json:"foodTotalPrice"`     //餐食总价格(分)
	CatTotalPrice   float64 `json:"homestayTotalPrice"` //民宿总价格(分)
	Remark          string  `json:"remark"`             //备注
	LivePeopleNum   int64   `json:"livePeopleNum"`      //实际入住人数
	NeedFood        int64   `json:"needFood"`           //0:不需要餐食 1:需要参数
	PayTime         int64   `json:"payTime"`            //支付时间
	PayType         string  `json:"payType"`            //支付类型
}
