// Code generated by goctl. DO NOT EDIT.
package types

type PetInfo struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Breed        string `json:"breed"`
	DateOfBirth  string `json:"date_of_birth"`
	Gender       string `json:"gender"`
	OwnerName    string `json:"owner_name"`
	OwnerContact string `json:"owner_contact"`
	Note         string `json:"note"`
	CreateTime   string `json:"create_string"`
	UpdateTime   string `json:"update_string"`
	DeleteTime   string `json:"delete_string"`
	DelState     int64  `json:"del_state"`
}

type PetReq struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Breed        string `json:"breed"`
	DateOfBirth  string `json:"date_of_birth"`
	Gender       string `json:"gender"`
	OwnerName    string `json:"owner_name"`
	OwnerContact string `json:"owner_contact"`
	Note         string `json:"note"`
}

type PetResp struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Breed        string `json:"breed"`
	DateOfBirth  string `json:"date_of_birth"`
	Gender       string `json:"gender"`
	OwnerName    string `json:"owner_name"`
	OwnerContact string `json:"owner_contact"`
	Note         string `json:"note"`
	CreateTime   string `json:"create_string"`
	UpdateTime   string `json:"update_string"`
	DeleteTime   string `json:"delete_string"`
	DelState     int64  `json:"del_state"`
	Version      int64  `json:"version"`
}
